// <auto-generated />
using System;
using GoodHamburguer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodHamburguer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GoodHamburguerDbContext))]
    partial class GoodHamburguerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GoodHamburguer.Infrastructure.Persistence.Entities.MenuItemEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("CategoryDisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Code");

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("GoodHamburguer.Infrastructure.Persistence.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DrinkItemCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SandwichItemCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SideItemCode")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DrinkItemCode");

                    b.HasIndex("SandwichItemCode");

                    b.HasIndex("SideItemCode");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("GoodHamburguer.Infrastructure.Persistence.Entities.OrderEntity", b =>
                {
                    b.HasOne("GoodHamburguer.Infrastructure.Persistence.Entities.MenuItemEntity", null)
                        .WithMany()
                        .HasForeignKey("DrinkItemCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GoodHamburguer.Infrastructure.Persistence.Entities.MenuItemEntity", null)
                        .WithMany()
                        .HasForeignKey("SandwichItemCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GoodHamburguer.Infrastructure.Persistence.Entities.MenuItemEntity", null)
                        .WithMany()
                        .HasForeignKey("SideItemCode")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
